version: '3'
services:
  ui-dev:
    build: ./cucumber-ui-devcontainer
    volumes:
      - ../..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - db
      - api
    env_file: ../../.envdev
    environment:
      - SENTRY_DSN=${SENTRY_DSN_UI}

  api:
    build: ../../api
    links:
      - db
      - kbsolver
    env_file: ../../.envdev
    environment:
      - SENTRY_DSN=${SENTRY_DSN_API}

  kbsolver:
    build: ../../kbsolver
    restart: always
    env_file: ../../.envdev
    environment:
      - SENTRY_DSN=${SENTRY_DSN_KBSOLVER}

  db:
    image: postgres
    restart: always
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file: ../../.envdev