kbsolver-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DEPLOY_NAME: kbsolver
    DOCKER_IMAGE_NAME: $DOCKER_DEPLOY_NAME:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" ./kbsolver
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_DEPLOY_NAME:latest"
        docker push "$DOCKER_DEPLOY_NAME:latest"
      fi
